# https://docs.docker.com/samples/library/elasticsearch/

version: "3"
services:
  elasticsearch:
    # image: "elasticsearch:latest"
    image: "elasticsearch:5.6.14-alpine"
    # volumes: 
    #  - $PWD/elasticsearch/config:/usr/share/elasticsearch/config
    #  - $PWD/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200"
      - "9300:9300"
